// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReferenceData.Infrastructure.Persistence;

#nullable disable

namespace ReferenceData.Infrastructure.Migrations
{
    [DbContext(typeof(ReferenceDataDbContext))]
    [Migration("20260427103005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReferenceData.Domain.ClaimStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClaimStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SUBMITTED",
                            Description = "Claim has been filed and is awaiting review.",
                            IsActive = true,
                            Name = "Submitted"
                        },
                        new
                        {
                            Id = 2,
                            Code = "UNDER_REVIEW",
                            Description = "A reviewer is actively assessing the claim.",
                            IsActive = true,
                            Name = "Under Review"
                        },
                        new
                        {
                            Id = 3,
                            Code = "APPROVED",
                            Description = "The claim has been accepted; payment will be processed.",
                            IsActive = true,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 4,
                            Code = "REJECTED",
                            Description = "The claim has been denied; no payment will be made.",
                            IsActive = true,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PAID",
                            Description = "Payment has been issued to the policy holder.",
                            IsActive = true,
                            Name = "Paid"
                        });
                });

            modelBuilder.Entity("ReferenceData.Domain.CoverageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CoverageTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FULL",
                            Description = "All-risk coverage.",
                            IsActive = true,
                            Name = "Full"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PARTIAL",
                            Description = "Named-perils coverage.",
                            IsActive = true,
                            Name = "Partial"
                        },
                        new
                        {
                            Id = 3,
                            Code = "THIRD_PARTY",
                            Description = "Covers legal liability to third parties.",
                            IsActive = true,
                            Name = "Third Party"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CATASTROPHIC",
                            Description = "Covers only extreme, large-scale loss events.",
                            IsActive = true,
                            Name = "Catastrophic"
                        });
                });

            modelBuilder.Entity("ReferenceData.Domain.PolicyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PolicyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AVIATION",
                            Description = "Insurance for aircraft, airlines, airports, and aviation-related liability.",
                            IsActive = true,
                            Name = "Aviation"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ENERGY",
                            Description = "Insurance for oil rigs, wind farms, refineries, pipelines, etc.",
                            IsActive = true,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MARINE",
                            Description = "Insurance for ships, cargo, ports, and waterways.",
                            IsActive = true,
                            Name = "Marine"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CYBER",
                            Description = "Insurance against data breaches and ransomware attacks.",
                            IsActive = true,
                            Name = "Cyber"
                        },
                        new
                        {
                            Id = 5,
                            Code = "LIABILITY",
                            Description = "General commercial liability insurance.",
                            IsActive = true,
                            Name = "Liability"
                        });
                });

            modelBuilder.Entity("ReferenceData.Domain.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NSW",
                            IsActive = true,
                            Name = "New South Wales"
                        },
                        new
                        {
                            Id = 2,
                            Code = "VIC",
                            IsActive = true,
                            Name = "Victoria"
                        },
                        new
                        {
                            Id = 3,
                            Code = "QLD",
                            IsActive = true,
                            Name = "Queensland"
                        },
                        new
                        {
                            Id = 4,
                            Code = "WA",
                            IsActive = true,
                            Name = "Western Australia"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SA",
                            IsActive = true,
                            Name = "South Australia"
                        },
                        new
                        {
                            Id = 6,
                            Code = "TAS",
                            IsActive = true,
                            Name = "Tasmania"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ACT",
                            IsActive = true,
                            Name = "Australian Capital Territory"
                        },
                        new
                        {
                            Id = 8,
                            Code = "NT",
                            IsActive = true,
                            Name = "Northern Territory"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
